name = "vales"

packages = [
    #"cargo",
    #"cargo-edit",
    #"cargo.passthru.rustc",
    #"rustc",
	#"rustfmt",
	#"rustPlatform.rustcSrc",
	#"clippy",cat
	"vales.pkgs.rust",
    "rust-analyzer",
]
